name: Terraform Azure Deployment

on:
  push:
    branches:
      - main  # Trigger workflow on push to main branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.10.5

    # Log in to Azure using Service Principal
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Initialize Terraform
    - name: Initialize Terraform
      run: terraform init

    # Validate Terraform configuration
    - name: Validate Terraform configuration
      run: terraform validate

    # Plan the Terraform deployment
    - name: Plan Terraform deployment
      run: terraform plan -var-file="values.tfvars"

    # Apply Terraform configuration
    # - name: Apply Terraform deployment
    #   run: terraform apply -auto-approve -var-file="values.tfvars"
